/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <string.h>
/* Header for class com_example_testjni_MainActivity */

#ifndef _Included_com_example_testjni_MainActivity
#define _Included_com_example_testjni_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testjni_MainActivity
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_testjni_MainActivity_getStringFromC
  (JNIEnv *, jobject);


JNIEXPORT jdouble JNICALL Java_com_example_testjni_MainActivity_getString2FromC
  (JNIEnv *, jobject,jstring);


#ifdef __cplusplus
}
#endif
#endif
